# action 流名称
name: build-and-deploy Go

on:
  push:        #监听 push 事件
    branches: 
      - main   #监听分支
      
jobs:
  build:
    # 不要用22的版本
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: 1、set up golang 安装 go 环境
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: 2、go build 打包go程序
      run: GOOS=windows GOARCH=amd64  go build -ldflags="-s -w" -trimpath -o PassGet main.go
