name: Go Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        go-version: [1.20.14]
        arch: [amd64, 386]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build for Windows
        run: |
          env GOOS=windows GOARCH=${{ matrix.arch }} go build -ldflags="-s -w" -trimpath -o mybinary_${{ matrix.arch }}.exe main.go

      - name: Upload Release
        uses: actions/upload-artifact@v2
        with:
          name: mybinary-${{ matrix.arch }}
          path: mybinary_${{ matrix.arch }}.exe
