name: goreleaser

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: "Check out code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Set up Go"
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.14
      -
        name: Install UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true

      - name: UPX version
        run: upx --version

      - name: "Create release on GitHub"
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: "release --snapshot --clean -f .github/conf/.goreleaser.yml"
          workdir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Zip files
        run: zip -r dist/PassGet_archive.zip dist/*
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
           repo_token: ${{ secrets.GITHUB_TOKEN }}
           file: dist/PassGet_archive.zip
           tag: ${{ github.ref }}
           overwrite: true
           file_glob: true
           draft: false #编译完成后 会自动发布到release
